# Generated by Django 2.2.4 on 2019-08-28 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20190828_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_user',
        ),
        migrations.AlterModelTable(
            name='user_user',
            table='User_user',
        ),
    ]
